import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, LegalSection } from "@/components/legal/LegalPage";
import { SITE } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "What personal data USA2BIH collects when you browse vehicles, send an inquiry or open an account, how it is used, and who it is shared with.",
};

const UPDATED = "16 September 2026";

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" updated={UPDATED}>
      <LegalSection heading="Who this policy covers">
        <p>
          This policy describes how USA2BIH, operating from Sarajevo, Bosnia and Herzegovina,
          handles personal data collected through this website. Questions about anything below can
          be sent to <a href={`mailto:${SITE.email}`}>{SITE.email}</a>.
        </p>
      </LegalSection>

      <LegalSection heading="What we collect">
        <p>We collect only what a given action requires.</p>
        <ul className="flex flex-col gap-2">
          <li>
            <strong>Browsing the site.</strong> Vehicle pages count how many times they have been
            opened. That counter is not tied to you.
          </li>
          <li>
            <strong>Contact form.</strong> Your name, email address, subject and message.
          </li>
          <li>
            <strong>Vehicle inquiry.</strong> Your name, email address, an optional phone number,
            your message, and which vehicle it concerns.
          </li>
          <li>
            <strong>Account.</strong> Your name, email address and password, handled by our
            authentication provider. You can add a phone number and preferred language to your
            profile.
          </li>
          <li>
            <strong>While signed in.</strong> Vehicles you save or view, calculations you choose to
            keep, import orders opened for you, and documents uploaded against them.
          </li>
        </ul>
      </LegalSection>

      <LegalSection heading="Why we hold it">
        <p>
          Contact and inquiry details are used to answer you and to quote an import. Account and
          import data is used to run the service you signed up for and to keep a record of a
          transaction we are party to. We do not build advertising profiles and we do not sell
          personal data.
        </p>
      </LegalSection>

      <LegalSection heading="Who processes it for us">
        <ul className="flex flex-col gap-2">
          <li>
            <strong>Neon.</strong> Hosts the database and the authentication service that stores
            account credentials and sessions.
          </li>
          <li>
            <strong>Vercel.</strong> Hosts the site and stores files uploaded to it, including
            vehicle images and import documents.
          </li>
          <li>
            <strong>Resend.</strong> Delivers notification email generated by the contact and
            inquiry forms.
          </li>
        </ul>
        <p>
          Each of these processes data on our instructions. Data may be stored on servers outside
          Bosnia and Herzegovina, including in the European Union and the United States.
        </p>
      </LegalSection>

      <LegalSection heading="Cookies and local storage">
        <p>
          Signing in sets one cookie that holds your session so you stay signed in between pages.
          It is required for the account area to work, and removing it signs you out. The vehicle
          comparison tray keeps your selection in your browser&apos;s local storage; it never
          reaches our servers and clearing site data removes it. We do not use advertising or
          analytics cookies.
        </p>
      </LegalSection>

      <LegalSection heading="How long we keep it">
        <p>
          Contact messages and inquiries are kept while they are being dealt with and afterwards as
          a record of the enquiry. Account, import and document records are kept for as long as the
          account is open, and after closure for as long as tax and customs record-keeping
          obligations require.
        </p>
      </LegalSection>

      <LegalSection heading="Your rights">
        <p>
          You can ask for a copy of the personal data we hold about you, ask us to correct it, or
          ask us to delete it where we are not required to keep it. Write to{" "}
          <a href={`mailto:${SITE.email}`}>{SITE.email}</a> and we will respond within 30 days. You
          can change your own name, phone number and language at any time under{" "}
          <Link href="/dashboard/profile">profile settings</Link>.
        </p>
      </LegalSection>

      <LegalSection heading="Changes">
        <p>
          If this policy changes, the date at the top of this page changes with it. Material
          changes affecting account holders will also be sent by email.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
